### ISSUE TITLE
v1.4.1(29) - README.md “#” 位置連結轉跳

### ISSUE THREAD

**Issue by AllenGuan** [jkpang/PPHub-Feedback#101]
範例：[後端架構師技術圖譜](https://github.com/xingshaocheng/architect-awesome)

Environment: iPhone 6s Plus - iOS11.4 - PPHub v1.4.1(29)

**Comment by jkpang** [comment]
現在點擊“#”位置，只能跳轉新界面顯示對應的內容，無法做到在當前界面跳轉對應的內容
