### ISSUE TITLE
v1.4.1(29) - 無README.md錯誤

### ISSUE THREAD

**Issue by AllenGuan** [jkpang/PPHub-Feedback#102]
[範例](https://github.com/LucasHF/GitHub)

Environment: iPhone 6s Plus - iOS11.4 - PPHub v1.4.1(29)

**Comment by jkpang** [comment]
無README.md錯誤，說明此倉庫沒有設置README.md文件，所以才顯示此頁面

**Comment by AllenGuan** [comment]
@jkpang
不考慮改善嗎？

**Comment by jkpang** [comment]
這個無法改善，GitHub用戶的倉庫不設置README.md文件我也沒辦法，我沒有權限給這個倉庫Create這個文件 @AllenGuan
