### ISSUE TITLE
v1.4.2(30) - 建议增加下载功能

### ISSUE THREAD

**Issue by rollo-zhou** [jkpang/PPHub-Feedback#107]
每次打开都从服务器拉取太耗时 尤其是弱网络环境 建议增加下载功能 这样常用的项目打开体验好很多

运行环境: iPhone 6 - iOS10.3 - PPHub v1.4.2(30)

**Comment by jkpang** [comment]
PPHub并不想发展成一个专业查看GitHub代码的工具，个人觉得在手机上看代码太鸡肋，在手机上看代码纯粹是为了应应急。GitHub上的代码仓库里面包含了许多非代码文件，且体积较大，在弱网环境下的体验反而没有直接加载单个文件来好，下载代码库的功能我在后续的版本会尝试，但不一定会上线这个功能哈。 @rollo-zhou
