### ISSUE TITLE
v1.4.2(30) - 按语言搜索符号会被过滤

### ISSUE THREAD

**Issue by Longston** [jkpang/PPHub-Feedback#108]
比如我要单独查看C#的人气仓库，选择C#语言，筛选出来的结果却是C的。

运行环境: iPhone 6s Plus - iOS12.0 - PPHub v1.4.2(30)

**Comment by jkpang** [comment]
感谢反馈，下个版本修复此问题

**Comment by jkpang** [comment]
1.5.0已审核通过，已修复此BUG @Longston

**Comment by Longston** [comment]
谢谢 现在去更新看看🙏
