### ISSUE TITLE
代码库打不开

### ISSUE THREAD

**Issue by JesseEisen** [jkpang/PPHub-Feedback#11]
想打开看某个repo里面的代码，点击后没有跳转。

机器：iphone6s

**Comment by jkpang** [comment]
PPHub暂时只能通过网页的方式查看代码, 经过测试也是可以查看代码的.请问你查看Repo的代码是怎么操作的?

**Comment by JesseEisen** [comment]
在repository页面，点开repo的标题，没有反应。下方的watch等，以及 issue、PR、readme都是可以点开。

**Comment by jkpang** [comment]
下个版本(v1.1.0)将支持查看代码 @JesseEisen

**Comment by jkpang** [comment]
最新版本已支持查看代码, 欢迎更新
