### ISSUE TITLE
v1.5.0(33) - Issue and Project for organization 

### ISSUE THREAD

**Issue by andrewtw** [jkpang/PPHub-Feedback#112]
Hi,

這個app真的是目前UI最乾淨的一款（付費亂買了許多其他的app，深感失望）
但是，對於org，希望能呈現in-app的issue跟project進度狀況（kanban）
而不是打開built-in的browser

Environment: iPhone 6s - iOS11.4 - PPHub v1.5.0(33)

**Comment by jkpang** [comment]
非常感謝對PPHub的支持！在未來我會盡量完善PPHub Native的體驗 @andrewtw

**Comment by jkpang** [comment]
hello，最新版v1.7.1优化了App内查看issues与pulls的体验，如果没有更新可以试试哦！
