### ISSUE TITLE
v1.5.1(37) - Profile模块下拉刷新有bug

### ISSUE THREAD

**Issue by windstormeye** [jkpang/PPHub-Feedback#113]
当我打开app时，来到profile模块，然后下拉刷新，发现以往正常的下拉刷新并没有归位，而是又往下偏移了导航栏的高度，且蓝白渐变的动态线，变成了一个蓝白原点。

（如果能给您发图就好了🌚

运行环境: iPhone 7 - iOS11.4 - PPHub v1.5.1(37)

**Comment by jkpang** [comment]
Hello，请问这种情况是必现吗，有没有复现的步骤？我刚刚使用相同系统环境的iPhone7模拟器和真机，下拉刷新了好久都没有重现这个BUG，要不可以试试杀掉进程后重试，或者卸载重装看看😂😂😂 @windstormeye
