### ISSUE TITLE
v1.5.1(37) - AFNNetworking 搜索不出来

### ISSUE THREAD

**Issue by wxiubin** [jkpang/PPHub-Feedback#114]
运行环境: iPhone 6s - iOS12.0 - PPHub v1.5.1(37)

**Comment by jkpang** [comment]
刚刚测试了一下，网页端和APP端的搜索 **AFNNetworking**的结果一样：    

![image](https://user-images.githubusercontent.com/17583451/42569132-183e1394-8542-11e8-8c72-69a3683d4a7e.png)
![image](https://user-images.githubusercontent.com/17583451/42569366-e135853e-8542-11e8-8058-cd9baa1866ca.png)

===========================================================================

**如果搜索的是 “AFNetworking” 就没错了**      


![image](https://user-images.githubusercontent.com/17583451/42569431-0d0d63f2-8543-11e8-9d73-81773b272e25.png)


@wxiubin
