### ISSUE TITLE
v1.5.1(37) - 切换分支问题

### ISSUE THREAD

**Issue by elfertower** [jkpang/PPHub-Feedback#115]
在仓库页面没有找到如何切换分支

运行环境: iPad Mini 3 - iOS11.4.1 - PPHub v1.5.1(37)

**Comment by jkpang** [comment]
目前还没有切换分支的功能哈？默认是master

**Comment by elfertower** [comment]
以后会加上切换分之的功能吗？有没有这方面的计划？

**Comment by jkpang** [comment]
嗯嗯，以后会将这个功能加上

**Comment by elfertower** [comment]
期待你的改进和完善

**Comment by jkpang** [comment]
目前最新版本v1.7.1已可以在仓库详情界面切换分支，快去更新吧！ @elfertower
