### ISSUE TITLE
v1.5.1(37) - 咨询下

### ISSUE THREAD

**Issue by KingggWS** [jkpang/PPHub-Feedback#116]
你好开发者，我不是程序员热爱折腾，用pphub就是方便star 然后我发现我下载一些东西他会显示太大，能解决吗

運行環境: iPhone 8 - iOS11.4.1 - PPHub v1.5.1(37)

**Comment by jkpang** [comment]
你好，PPHub 没有下载功能，请问你是用什么App下载的什么东西？是什么显示太大，图片，字体，还是存储容量？

**Comment by jkpang** [comment]
sorry，我不是固件工程师，不懂这个

**Comment by KingggWS** [comment]
好吧，谢谢啦，很喜欢你的app

                                                        ————King👑
