### ISSUE TITLE
v1.5.1(37) - 适配器iPhoneX有问题

### ISSUE THREAD

**Issue by liuyangzuo** [jkpang/PPHub-Feedback#119]
底部有遮挡

运行环境: iPhone X - iOS12.0 - PPHub v1.5.1(37)

**Comment by liuyangzuo** [comment]
![3751533730579_ pic_hd](https://user-images.githubusercontent.com/8985760/43836436-f374ffd4-9b47-11e8-86f4-c06904e30ecb.jpg)

**Comment by jkpang** [comment]
v1.5.2已修复此问题，可前往App Store更新 @liuyangzuo

**Comment by liuyangzuo** [comment]
@jkpang  cool 已经更新了
