### ISSUE TITLE
Add star action for a repo

### ISSUE THREAD

**Issue by Sorosliu1029** [jkpang/PPHub-Feedback#12]
Could add a star action for a repo that user is interested in, for example, from trending list, or in repo detail page?

**Comment by Sorosliu1029** [comment]
Refer to #9 . Hold and star....Orz

**Comment by jkpang** [comment]
V1.0.1 has passed the apple audit today, and the new version has repaired the problem
V1.0.1今天已通过苹果审核, 新版本已修复该问题
