### ISSUE TITLE
v1.5.3(49) - 关于 里的 评分鼓励，点击跳转 App ...

### ISSUE THREAD

**Issue by ChengLuffy** [jkpang/PPHub-Feedback#121]
关于 里的 评分鼓励，点击跳转 App Store 后会提示 当你使用 prerelease 应用时，不能写评价。

运行环境: iPhone 6 - iOS12.0 - PPHub v1.5.3(49)

**Comment by jkpang** [comment]
可能是因为你是iOS 12Beta版系统，所以不能评价，需要等到正式版
