### ISSUE TITLE
v1.6.0(51) - 希望可以 App 内回复 PR 和 is...

### ISSUE THREAD

**Issue by HuangXiZhou** [jkpang/PPHub-Feedback#122]
希望可以 App 内回复 PR 和 issue 感恩

运行环境: iPhone 8 - iOS11.4 - PPHub v1.6.0(51)

**Comment by jkpang** [comment]
这个功能在后续的计划中😁

**Comment by jkpang** [comment]
v1.8.0+版本已可以回复PR与Issue了哦, 记得更新~
