### ISSUE TITLE
v1.6.0(51) - 搜索那里每次切换语言之后  还需要重新点...

### ISSUE THREAD

**Issue by szweee** [jkpang/PPHub-Feedback#126]
搜索那里每次切换语言之后  还需要重新点击一下搜索按钮才行  有点麻烦，搜索那里选择语言也有点麻烦  重新启动都默认是所有语言

运行环境: iPhone X - iOS12.0 - PPHub v1.6.0(51)

**Comment by jkpang** [comment]
第一点事1.6.0的bug，新版已修复并提交审核，第二点在后续版本中会优化，感谢反馈

**Comment by jkpang** [comment]
v1.6.1已审核通过，已修复此bug @szweee
