### ISSUE TITLE
v1.6.1(58) - 希望能看到 activity 和 not...

### ISSUE THREAD

**Issue by zack9433** [jkpang/PPHub-Feedback#128]
希望能看到 activity 和 notification 

運行環境: iPhone 6 Plus - iOS11.4.1 - PPHub v1.6.1(58)

**Comment by jkpang** [comment]
其实News（底栏左起第二个）模块里面就可以同时看到用户关注的仓库、开发者的activity 和 notification了 @zack9433

**Comment by zack9433** [comment]
瞭解
