### ISSUE TITLE
v1.6.1(58) - 如果可以请开发者汉化全面一些谢谢🙏

### ISSUE THREAD

**Issue by lzr52o** [jkpang/PPHub-Feedback#131]
运行环境: iPhone 6s Plus - iOS12.0 - PPHub v1.6.1(58)

**Comment by jkpang** [comment]
Hello，不好意思哈，到现在才看见。PPHub目前只做了与GitHub内容不相关的汉化，我觉得觉得这样比较符合GitHub的传统，如果汉化 Star -> 星标、Fork -> 分叉..... 这样总感觉怪怪的，GitHub就只有英语一种语言，我认为有关于它的内容还是原生态的好一些。非常感谢您的反馈😊 @lzr52o
