### ISSUE TITLE
v1.6.1(58) - 界面做的不错，也挺流畅。不过里面很多链接...

### ISSUE THREAD

**Issue by javacodecreeks** [jkpang/PPHub-Feedback#134]
界面做的不错，也挺流畅。不过里面很多链接都是跳转到网页，这似乎不太好吧。另外一些功能还需要完善，望开发者继续加油！

运行环境: iPhone 6 - iOS11.2.6 - PPHub v1.6.1(58)

**Comment by jkpang** [comment]
Hello, PPHub v1.7.0已添加issue，Pull request原生列表，并增强了issue、PR详情的查看体验，快去更新吧！ @javacodecreeks
