### ISSUE TITLE
v1.6.2(59) - followers和following报...

### ISSUE THREAD

**Issue by chaoedu** [jkpang/PPHub-Feedback#136]
followers和following报404

运行环境: iPhone XS - iOS12.0 - PPHub v1.6.2(59)

**Comment by jkpang** [comment]
Hello，请问这种情况是每次操作必现的吗？我这边试了很久都没问题😂

**Comment by chaoedu** [comment]
应该是个别组织问题，比如Microsoft这种，对应接口：https://github.com/users/Microsoft/contributions， https://api.github.com/users/Microsoft/followers?page=1返回404，页面弹toast，不过不影响使用

**Comment by jkpang** [comment]
好的好的，我会抽时间修复这个问题，感谢反馈哈！

**Comment by chaoedu** [comment]
@jkpang 谢谢，用过的最好的移动客户端

**Comment by jkpang** [comment]
感谢感谢 @chaoedu
