### ISSUE TITLE
v1.6.2(59) - 每次更新后，很大几率所有设置被还原，已经...

### ISSUE THREAD

**Issue by aidevjoe** [jkpang/PPHub-Feedback#137]
每次更新后，很大几率所有设置被还原，已经发生两次。

Environment: iPhone X - iOS12.1 - PPHub v1.6.2(59)

**Comment by jkpang** [comment]
Sorry ，这次的1.6.2版本是我重构了代码，修改了设置存储的Key值，没有考虑到版本兼容的问题，以后我会尽量避免，非常抱歉哈！
