### ISSUE TITLE
经常出现404

### ISSUE THREAD

**Issue by LinMingQiang** [jkpang/PPHub-Feedback#139]

**Comment by jkpang** [comment]
你好，是在哪个页面会出现这样的情况？是在Trending页吗？

**Comment by LinMingQiang** [comment]
News。我换wifi还是4G都会，有时候一天都是404。有时候又是正常的。我还以为要翻墙之类的

**Comment by jkpang** [comment]
emmm...... ，这么奇怪？我这边的News还没有出现过这种情况，请问下你的App是最新的1.6.2版本不？Wifi和4g的网络提供商分别是哪家？我怀疑和网络有点关系，长城和电信的网络对GitHub的支持是最差的😂。

要不也可以卸载了重新下载试试看

**Comment by LinMingQiang** [comment]
联通的，1.6.2，ios 12。也是偶尔会出现，但是出现了就是一天或几天。下次我重新下载看看。（东西很好用）

**Comment by jkpang** [comment]
嗯嗯，那我这边也会持续跟进这个问题，感谢反馈！
