### ISSUE TITLE
支持app内网页密码填充

### ISSUE THREAD

**Issue by TioWang** [jkpang/PPHub-Feedback#14]
就像知乎app那样可以用iCloud钥匙串直接填充

运行环境: iPhone X - iOS11.2 - PPHub v1.0.0(1)

**Comment by jkpang** [comment]
您之前有在Safari登录过GitHub账号并记住密码了吗?,如果有过, 进入登录界面时可以使用密码填充的 @TioWang

**Comment by TioWang** [comment]
网页是正常有的诶，可是在软件登录的时候不能用

**Comment by jkpang** [comment]
恩恩, 知道了, 我会优化排查这个问题

**Comment by TioWang** [comment]
![559f6fda-61a6-4b66-85bc-ff957ebf20e5](https://user-images.githubusercontent.com/12782946/33063724-48521406-cede-11e7-8287-13ed5ab0f88b.png)

**Comment by TioWang** [comment]
app里要是可以直接回复不用通过内置网页就好了哈哈哈，做的很棒！

**Comment by jkpang** [comment]
因为有些用户的GitHub账号使用的是二次验证机制, 使用原生界面登录会比较麻烦, 使用GitHub官方网页授权登录也会安全些, 消除一些用户的顾虑 , 谢谢你的评价哈@TioWang

**Comment by jkpang** [comment]
#1

**Comment by jkpang** [comment]
我会尝试在后续的版本支持 1Password 填充密码, 我今天试了SFSafariViewController填充密码会有点问题,会导致用户不能更换其他的GitHub账号, 谢谢你的建议😊 @TioWang

**Comment by jkpang** [comment]
最新版本已支持1password登录
