### ISSUE TITLE
v1.6.2(59) 如果某个仓库的主分支是空的，进入查看代码界面会崩溃。

### ISSUE THREAD

**Issue by jaywang** [jkpang/PPHub-Feedback#147]
比如浏览 https://github.com/yichengchen/clashX 仓库

**Comment by jkpang** [comment]
好的，感谢反馈，我会尽快解决这个问题

**Comment by jkpang** [comment]
Hello，我刚刚用App Store最新版本的PPHub打开 https://github.com/yichengchen/clashX 仓库的代码界面，没有发生崩溃，请问是打开某个代码文件发生的崩溃吗？如果是的话，希望可以截图告诉我这个文件的名称哈 非常感谢你的反馈😊@jaywang

**Comment by jaywang** [comment]
[cid:f71b07d2-300e-4301-9d82-12d104812c00]

在我的设备上是点击如图箭头所指的地方发生crash


Rest Regards

Jaywang
<http://aka.ms/weboutlook>

________________________________
发件人: jkpang <notifications@github.com>
发送时间: 2018年10月16日 17:54
收件人: jkpang/PPHub-Feedback
抄送: jaywang; Mention
主题: Re: [jkpang/PPHub-Feedback] v1.6.2(59) 如果某个仓库的主分支是空的，进入查看代码界面会崩溃。 (#147)


Hello，我刚刚用App Store最新版本的PPHub打开 https://github.com/yichengchen/clashX 仓库的代码界面，没有发生崩溃，请问是打开某个代码文件发生的崩溃吗？如果是的话，希望可以截图告诉我这个文件的名称哈 非常感谢你的反馈😊@jaywang<https://github.com/jaywang>

**Comment by jaywang** [comment]
代码样式用的是github, 改成default就不crash了.再改回去也不crash了。 我再用用吧，如发现规律再反馈给你

**Comment by jkpang** [comment]
嗯嗯，可能是你从旧版升级到最新的v1.6.2发生的兼容性问题，导致其崩溃，卸载重装后没问题就没问题了，感谢反馈！ @jaywang
