### ISSUE TITLE
v1.6.2(59) - 无法查看私有仓库（GitHub Clas...

### ISSUE THREAD

**Issue by eric1932** [jkpang/PPHub-Feedback#148]
无法查看私有仓库（GitHub Classroom），即便有访问权限也会提示404

运行环境: iPhone XS - iOS12.0.1 - PPHub v1.6.2(59)

**Comment by jkpang** [comment]
仓库的详情页可以访问吗？还是说访问不了仓库里面的文件列表 @eric1932

**Comment by eric1932** [comment]
整个仓库404 Not Found
