### ISSUE TITLE
个人主页简介没有时，点击崩溃

### ISSUE THREAD

**Issue by ikewang** [jkpang/PPHub-Feedback#15]
github没有 个人简介时，点击头像进去主页，点击简介，应用崩溃

运行环境: iPhone 6s - iOS10.3.3 - PPHub v1.0.0(1)

**Comment by jkpang** [comment]
原因已找到, 下个版本更新修复

**Comment by jkpang** [comment]
V1.0.1今天已通过苹果审核, 新版本已修复该问题
