### ISSUE TITLE
v1.6.3(60) - 一个小问题 搜索界面什么都不写直接搜索 ...

### ISSUE THREAD

**Issue by lztbwlkj** [jkpang/PPHub-Feedback#151]
一个小问题 搜索界面什么都不写直接搜索 mb不消失了

运行环境: iPhone 7 - iOS12.0.1 - PPHub v1.6.3(60)

**Comment by jkpang** [comment]
Hello, PPHub v1.7.0已修复此问题，快去更新吧！ @lztbwlkj
