### ISSUE TITLE
v1.6.3(60) - 搜索选择c++结果是c

### ISSUE THREAD

**Issue by naiiu** [jkpang/PPHub-Feedback#152]
运行环境: iPhone 6s - iOS12.1 - PPHub v1.6.3(60)

**Comment by jkpang** [comment]
已知晓这个问题，将在下个版修复，感谢反馈 @naiiu

**Comment by jkpang** [comment]
Hello, PPHub v1.7.0已修复此问题，快去更新吧！ @naiiu
