### ISSUE TITLE
v1.6.3(60) - 仓库详情页面缺少相应的网站这一数据。

### ISSUE THREAD

**Issue by spencerwooo** [jkpang/PPHub-Feedback#153]
运行环境: iPhone 7 Plus - iOS12.0.1 - PPHub v1.6.3(60)

**Comment by spencerwooo** [comment]
如图所示，左侧为网页版、右侧为 PPHub。

![b658edc4-5655-42ec-b1b0-3bc0edb66a15](https://user-images.githubusercontent.com/32114380/48310500-4a272000-e5cb-11e8-8027-1fdae9c78a6a.jpeg)

**Comment by jkpang** [comment]
OK，已了解这个问题@spencerwooo

**Comment by jkpang** [comment]
Hello, PPHub v1.7.0已添加此功能，快去更新吧！ @spencerwooo

**Comment by spencerwooo** [comment]
更新了！nb！
