### ISSUE TITLE
v1.6.3(60) - 希望可以添加一个代码是否自动换行的选项

### ISSUE THREAD

**Issue by lifangjie** [jkpang/PPHub-Feedback#155]
运行环境: iPhone XS - iOS12.1 - PPHub v1.6.3(60)

**Comment by jkpang** [comment]
Hello，你的意思是在没有换行符\n的情况下，超过屏幕区域的文本不做换行处理吗？ @lifangjie

**Comment by lifangjie** [comment]
是的是的，相当于记事本的自动换行的开关，然后没开自动换行的时候可以加个全屏缩放或者横向滚动条。   非常感谢您的回复，大佬幸苦了。

发自我的 iPhone

**Comment by jkpang** [comment]
不是大佬哈😂。这个问题我会考虑的，因为显示代码是用的系统原生控件，你说的功能改动起来影响蛮大。不过你暂时可以点击 分享按钮 -> 打开网页 ，网页模式可以基本满足你说的这个功能
![qq20181114-132802](https://user-images.githubusercontent.com/17583451/48462003-51d80600-e811-11e8-95a8-ad9eda7e95d4.png)
![qq20181114-132823](https://user-images.githubusercontent.com/17583451/48462012-5997aa80-e811-11e8-9aed-efb6061a2188.png)
@lifangjie

**Comment by lifangjie** [comment]
好的，谢谢大佬

发自我的 iPhone
