### ISSUE TITLE
v1.7.0(61) - 大神，软件有TF版本么？麻烦加个，zha...

### ISSUE THREAD

**Issue by zhaozhining** [jkpang/PPHub-Feedback#158]
大神，软件有TF版本么？麻烦加个，zhaoan.cn@gmail.com

运行环境: iPhone 6s Plus - iOS12.0.1 - PPHub v1.7.0(61)

**Comment by jkpang** [comment]
暂时没有TF哦，以后有TF的话我会放出链接的
