### ISSUE TITLE
v1.7.0(61) - 是否可以给代码浏览加上不折行(unwra...

### ISSUE THREAD

**Issue by 2hu12** [jkpang/PPHub-Feedback#160]
是否可以给代码浏览加上不折行(unwrap)的选项？

运行环境: iPhone XS Max - iOS12.1 - PPHub v1.7.0(61)

**Comment by jkpang** [comment]
Hello，暂时还没有这个计划，具体原因可以查看 #155 这个issue哦！ @2hu12
