### ISSUE TITLE
v1.7.0(61) - 看不到wiki仓库，一下项目的说明都是在...

### ISSUE THREAD

**Issue by gushizone** [jkpang/PPHub-Feedback#161]
看不到wiki仓库，一下项目的说明都是在wiki中，看不到，太不方便了。

运行环境: iPhone 8 - iOS12.0.1 - PPHub v1.7.0(61)

**Comment by jkpang** [comment]
这个在计划中了，会在后续的版本上线 @gushizone

**Comment by jkpang** [comment]
v1.7.3已添加WiKi入口，已可以更新
