### ISSUE TITLE
v1.7.0(61) - 看代码界面，右下角总出现圆形的分享按钮，...

### ISSUE THREAD

**Issue by yikaiw** [jkpang/PPHub-Feedback#164]
看代码界面，右下角总出现圆形的分享按钮，影响专注。能不能把分享按钮固定在右上角的主题按钮旁边呢？

运行环境: iPhone X - iOS12.0.1 - PPHub v1.7.0(61)

**Comment by jkpang** [comment]
目前的设计是向上滑动会隐藏分享按钮，向下滑动显示。如你所说的分享按钮放在右上角目前布局还有点问题，我会考虑这个问题的，感谢反馈 @yikaiw

**Comment by jkpang** [comment]
感谢你的建议，下个版本我会将分享按钮放在右上角 @yikaiw

**Comment by jkpang** [comment]
最新版v1.7.1已优化此问题，快去更新吧！

**Comment by gswxy** [comment]
当初的浮动按钮使用挺方便，现在新版放在右上角感觉不方便了，能加个开关不？

**Comment by yikaiw** [comment]
感谢
