### ISSUE TITLE
v1.7.0(61) - 从opener复制链接自动跳转到项目是空...

### ISSUE THREAD

**Issue by gswxy** [jkpang/PPHub-Feedback#165]
从opener复制链接自动跳转到项目是空白的，打不开。

运行环境: iPhone 6s - iOS12.0.1 - PPHub v1.7.0(61)

**Comment by gswxy** [comment]
居然和opener有联动，希望能修复这个错误。

**Comment by jkpang** [comment]
这不是PPHub的这边的问题，PPHub只是暴露出接口，由Opener传输给PPHub对应的正确参数给接口来打开对应的界面。您应该向Opener的作者反馈这个问题，由他来修改 @gswxy

**Comment by jkpang** [comment]
经过调试，是Opener通过PPHub打开仓库时，只带过来了“user”用户名参数，而仓库的名称是空白的。之前Opener是正常的，可能是作者更新版本时修改了代码，才导致此错误 @gswxy

**Comment by gswxy** [comment]
那你跟opener作者沟通下，把这个问题解决了。虽然复制也能打开，但是还是没opener方便一些。

**Comment by jkpang** [comment]
正在沟通。PPHub也有Safari浏览器插件，打开比Opener更方便。
![image](https://user-images.githubusercontent.com/17583451/49801783-1257f780-fd86-11e8-8402-653764d8bc24.png)
@gswxy

**Comment by jkpang** [comment]
经过沟通，Opener用户已经修复了这个问题。你现在可以先打开Opener主App一会儿，等匹配规则同步到本地后，就可以通过Opener插件打开了

**Comment by gswxy** [comment]
可以了。谢谢开发者解决这个问题！
