### ISSUE TITLE
v1.7.1(68) - Sometimes I need to ...

### ISSUE THREAD

**Issue by xAlien95** [jkpang/PPHub-Feedback#168]
Sometimes I need to refresh the webview for Issues and Pull Request. Is it possible to do a refresh whenever a new webview is shown?

Thank you for this awesome and stilish app, it’s one of my favorites!

Environment: iPhone XS Max - iOS12.0.1 - PPHub v1.7.1(68)

**Comment by jkpang** [comment]
Hello, I will improve this issue in the next version, thank you very much for your feedback! @xAlien95

**Comment by jkpang** [comment]
PPHub v1.7.2 has been released and this problem has been optimized🍻 @xAlien95

**Comment by xAlien95** [comment]
@jkpang, thanks!
