### ISSUE TITLE
iPad兼容性问题

### ISSUE THREAD

**Issue by Renxusheng** [jkpang/PPHub-Feedback#17]
希望可以兼容iPad横屏模式

Environment: iPad6,11 - iOS11.1 - PPHub v1.0.0(1)

**Comment by jkpang** [comment]
横屏适配会有点麻烦, 我会在后续的版本中尝试下最完美的解决办法, 感谢您的使用 @Renxusheng

**Comment by jkpang** [comment]
v1.1.1已发布, 请到App Store更新哦
