### ISSUE TITLE
v1.7.1(68) - 小组件里显示的commit情况与app中...

### ISSUE THREAD

**Issue by cjwcommuny** [jkpang/PPHub-Feedback#171]
小组件里显示的commit情况与app中显示的不一致

运行环境: iPhone 6s - iOS12.1 - PPHub v1.7.1(68)

**Comment by cjwcommuny** [comment]
似乎并不一样...
![img_4052](https://user-images.githubusercontent.com/23581749/49371855-c7aa0000-f733-11e8-8d0a-e4167f2f3425.jpg)
![img_4053](https://user-images.githubusercontent.com/23581749/49371856-c8429680-f733-11e8-8d8a-976d2382db77.jpg)

**Comment by jkpang** [comment]
我明白了，小组件显示的是你公开库的提交量；APP内部是公开库+私有库总提交量。奇怪了，我以前早就修复好了的，我明天找找原因

**Comment by jkpang** [comment]
Hello，今天我问了另外有私有库一个用户commits，他的小组件与App内的提交量都是一致的，要不你卸载重装后试试？ @cjwcommuny

**Comment by cjwcommuny** [comment]
找到问题了，似乎是因为我之前关闭了 private contributions 选项
<img width="786" alt="2018-12-06 11 03 27" src="https://user-images.githubusercontent.com/23581749/49558618-a66d2d80-f946-11e8-8c36-ebbbc81fa2e0.png">
