### ISSUE TITLE
v1.7.1(68) - 执行 unstar 操作时大机率闪退。

### ISSUE THREAD

**Issue by FrankYang4** [jkpang/PPHub-Feedback#173]
运行环境: iPhone 6s Plus - iOS12.1 - PPHub v1.7.1(68)

**Comment by jkpang** [comment]
嗯嗯，在仓库列表界面并且仓库Star > 1000时，进行Star就会闪退，我会在下个版本修复这个问题！非常感谢你的反馈！😊

**Comment by jkpang** [comment]
v1.7.3已修复此问题，已可以更新
