### ISSUE TITLE
v1.7.1(68) - Cannot open with ope...

### ISSUE THREAD

**Issue by kid1412621** [jkpang/PPHub-Feedback#178]
Cannot open with openner 

Environment: iPhone 6s - iOS12.1.1 - PPHub v1.7.1(68)

this is official reply from openner:
![image](https://user-images.githubusercontent.com/26278054/49711705-d6d10680-fc7b-11e8-8f52-33edc1d99473.png)

**Comment by kid1412621** [comment]
I tested with the url ---- github.com , doesn't work.
And I test this project url , it can open, but got 404 error.

**Comment by jkpang** [comment]
After communication, the Opener author has fixed this problem. You can open the Opener program for a while, and wait for the synchronization matching rule to succeed before you can use it. @kid1412621

**Comment by kid1412621** [comment]
Cool, I saw the developer of opener tweeted for pphub. 😀
