### ISSUE TITLE
URL scheme to open issues?

### ISSUE THREAD

**Issue by timonus** [jkpang/PPHub-Feedback#179]
I'm the developer of [Opener](https://www.opener.link), which supports PPHub. Does PPHub have a way of deep linking into the app to navigate to specific issues? Some of my users have requested it, and your competitor GitHawk supports it.

**Comment by jkpang** [comment]
Cool!!! I will implement this feature as soon as possible, thank you very much. I will contact you after completing this function. @timonus

**Comment by jkpang** [comment]
PPHub v1.7.2 has been released and supports opening specific issues through URL Schemes.
URL Schemes: 
1. Open user: `pphub://user?login=`
2. Open repo: `pphub://repo?owner=&repo=`
3. Open a issue: `pphub://issue?owner=&repo=&number=`
4. Open a pull request: `pphub://pull?owner=&repo=&number=`   

**Also in App, `Profile - > About - > URL Schemes` can be quickly replicated**   
@timonus

**Comment by jkpang** [comment]
My users gave me feedback that using Opener to open PPHub's warehouse was empty. After debugging, this is because Opener only passes an owner parameter to PPHub, which is caused by empty repo parameter (example: `pphub://repo?owner=jkpang&repo=""`). I hope you can fix this problem. Thanks！！！

**Comment by timonus** [comment]
Excellent! I've added support for opening issues and pull requests in 
https://github.com/timonus/OpenerManifest/commit/e2fc49122871fa8cb8814130db63a01eafdd6a24, and I fixed the issue you mentioned opening repos in 
https://github.com/timonus/OpenerManifest/commit/6af85272964aec66caeb5d68ce59cffb2eaefcb6.

Thanks for adding this!
