### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by KeatingPeng** [jkpang/PPHub-Feedback#18]
**Gist 入口**：能够查看 Gist 代码

**README.md**：希望能够直接在客户端上查看 README.md 而不是跳转到网页。

**组织结构**：能够查看一个项目的组织结构

**Comment by jkpang** [comment]
第1点和第3点功能有计划在以后的版本中陆续推出
第2点我尝试过很多方法去加载README.md文件, 但效果都不太理想, 主要是MarkDown中的图片不能显示 , 现在最好的体验依然是显示网页, 配合SFSafariViewController的阅读模式, 在部分README网页的显示中体验更佳 @KeatingPeng

**Comment by jkpang** [comment]
README.md的显示问题正在优化当中, 经过各种实验,已经有了比较好的解决方案, 感谢反馈!

**Comment by jkpang** [comment]
新版本1.1.0已上架App Store
1.README的已经去掉直接显示网页, 体验更加纯粹
2.已经可以查看项目的组织结构和项目代码
3.Gitst入口暂时没有, 可以给我提一个新的Issue哈 @KeatingPeng
