### ISSUE TITLE
v1.7.1(68) - 代码显示可以更美观一点，希望当单行代码过...

### ISSUE THREAD

**Issue by lushans** [jkpang/PPHub-Feedback#181]
代码显示可以更美观一点，希望当单行代码过长时也不要默认换行显示

运行环境: iPhone 6s - iOS12.1 - PPHub v1.7.1(68)

**Comment by jkpang** [comment]
Hello，暂时还没有这个计划，具体原因以及替代方案可以查看 #155 这个issue哦！ @lushans

**Comment by lushans** [comment]
好的 ，我觉得您以后可以考虑一下 美化一下显示效果

**Comment by jkpang** [comment]
嗯嗯，好的😊
