### ISSUE TITLE
v1.7.1(68) - Issue 详情h5会有缓存看不到最近的...

### ISSUE THREAD

**Issue by SilenceLove** [jkpang/PPHub-Feedback#182]
Issue 详情h5会有缓存看不到最近的内容

运行环境: iPhone X - iOS12.1 - PPHub v1.7.1(68)

**Comment by jkpang** [comment]
下个版本将去掉缓存，目前的版本可以点击底部栏的刷新按钮获取最新数据

**Comment by jkpang** [comment]
是这个刷新按钮，issue详情界面的这个底栏是  上拉隐藏，下拉显示 @SilenceLove 
![image](https://user-images.githubusercontent.com/17583451/49848088-66a6ba00-fe0e-11e8-8904-889fb3776839.png)

**Comment by SilenceLove** [comment]
3q,, 刷新一下确实出来了...

**Comment by jkpang** [comment]
v1.7.3已优化此问题，已可以更新
