### ISSUE TITLE
v1.7.1(68) - .ipynb文件支持差 希望作者能够优化...

### ISSUE THREAD

**Issue by yangsoon** [jkpang/PPHub-Feedback#183]
.ipynb文件支持差 希望作者能够优化这一部分 作者加油💪

运行环境: iPhone 8 - iOS12.1 - PPHub v1.7.1(68)

**Comment by PPPang** [comment]
这个暂时就优化不了，有点难搞😂。建议还是在PC上或专门适用的此类文件的软件上看

**Comment by jkpang** [comment]
这个暂时就优化不了，有点难搞😂。建议还是在PC上或专门适用的此类文件的软件上看

**Comment by jkpang** [comment]
你好，v1.9.0已审核通过，现在已可以查看.ipynb文件 @yangsoon
