### ISSUE TITLE
v1.7.1(68) - App 内发现有些github 库介绍里...

### ISSUE THREAD

**Issue by tisfeng** [jkpang/PPHub-Feedback#184]
App 内发现有些github 库介绍里的链接打不开404，比如有个🔗https://github.com/ibireme/YYAsyncLayer.git （有些库里放的链接就是这种格式），这里应该处理一下后面的.git

运行环境: iPhone 6s - iOS12.1.1 - PPHub v1.7.1(68)

**Comment by jkpang** [comment]
v1.7.3已优化此问题，已可以更新
