### ISSUE TITLE
v1.7.2(69) - 王者荣耀分享到QQ结果跳到pphub……

### ISSUE THREAD

**Issue by it5200** [jkpang/PPHub-Feedback#188]
运行环境: iPhone 8 Plus - iOS12.1.2 - PPHub v1.7.2(69)

**Comment by jkpang** [comment]
糟糕！我的错，我会尽快修复。非常抱歉😢

**Comment by jkpang** [comment]
Hello ，你看下其他应用分享到QQ还会不会跳到PPHub？我这边试了好几个应用都不会

**Comment by it5200** [comment]
我点的是王者荣耀里的分享会跳到pphub，系统分享则不会

**Comment by jkpang** [comment]
奇怪，我刚下载了王者荣耀然后分享，也没有跳到PPHub 。那你手机上的其他应用呢？比如：京东、新闻类App、美团...这些应用会不会跳PPHub？我这边试了都不会😂

**Comment by it5200** [comment]
……

**Comment by it5200** [comment]
不要用系统的隔空投送

**Comment by jkpang** [comment]
我没有用系统的隔空投送，刚关了隔空投送，再去用App内的分享也没有跳PPHub

**Comment by it5200** [comment]
好吧( ｡･-･｡ )

**Comment by jkpang** [comment]
我知道原因了，是我写代码时手抖了。只是有点好奇这里面跳转优先级，我会尽快修复，希望明天可以通过审核，感谢反馈

**Comment by it5200** [comment]
找到原因就好

**Comment by jkpang** [comment]
v1.7.3已修复此问题，已可以更新
