### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by Luuur** [jkpang/PPHub-Feedback#19]
News一直显示未能获取到数据

运行环境: iPhone 6s Plus - iOS10.3.3 - PPHub v1.0.0(1)

**Comment by jkpang** [comment]
The News module shows the dynamics of your Watch repository and the Following developer
1. no Watch warehouse /Following developer;
2.Watch warehouse /Following developer is not dynamic
You can pay more attention to your favorite warehouse and developer, and the data will show up then
*****************************************
News模块显示的是你Watch的仓库以及Following开发者的动态.未获取到数据说明你
1.没有Watch仓库/Following开发者;
2.Watch仓库/Following开发者没有动态
你可以多关注你喜欢的仓库和开发者, 到时候就会有数据显示出来
![image](https://user-images.githubusercontent.com/17583451/33116225-f6fccab2-cf9e-11e7-95b4-842bf19171da.png)
