### ISSUE TITLE
v1.7.3(70) - ERADME链接🔗跳转出现404

比如...

### ISSUE THREAD

**Issue by tisfeng** [jkpang/PPHub-Feedback#192]
ERADME链接🔗跳转出现404

比如美团的新开源的库Graver  https://github.com/Meituan-Dianping/Graver/blob/master/README.md

其README里的『框架概述』链接就打不开，网页查看这个链接是https://github.com/Meituan-Dianping/Graver/blob/master/docs/FrameworkOverview.md
而App中查看的链接不一样，中间少了docs，404

运行环境: iPhone 6s - iOS12.1.1 - PPHub v1.7.3(70)

**Comment by tisfeng** [comment]
咦，这会好像又正常了？！

**Comment by jkpang** [comment]
嗯嗯，我试了下也是正常的
