### ISSUE TITLE
v1.7.3(70) - 浏览corefx代码，src路径，软件只...

### ISSUE THREAD

**Issue by solicice** [jkpang/PPHub-Feedback#193]
浏览corefx代码，src路径，软件只显示十几个项目，实际有几十个.

运行环境: iPad Pro9.7 Inch - iOS12.1.3 - PPHub v1.7.3(70)

**Comment by jkpang** [comment]
我刚刚看了你说的corefx仓库，src路径下我这边显示的有60+个文件夹，不止十几个
