### ISSUE TITLE
图标不显示

### ISSUE THREAD

**Issue by Ansion-bo** [jkpang/PPHub-Feedback#2]
icon不显示

运行环境: iPhone X - iOS11.1.1 - PPHub v1.0.0(1)

**Comment by jkpang** [comment]
请问是什么icon不显示?

**Comment by jkpang** [comment]
我这边没有复现此问题, V1.0.1版本今天已通过苹果审核, 可以更新后再看, 如果问题还存在, 可以再次激活这个问题,希望能详细描述下问题的所在哈, 感谢
