### ISSUE TITLE
如何查看自己star的项目呢

### ISSUE THREAD

**Issue by HasjOH** [jkpang/PPHub-Feedback#20]
如题

运行环境: iPhone 6 Plus - iOS11.2 - PPHub v1.0.0(1)

**Comment by jkpang** [comment]
在 "Profile" 界面, 任意点击Repositories / Followers / Following 进入分页列表, 点击Star标题项即可看到自己Star的项目. 这部分在以后的版本中我会考虑以更直观的方式展示出来
![image](https://user-images.githubusercontent.com/17583451/33156542-a0b6e380-d035-11e7-91cc-cef6b026d284.png)
![image](https://user-images.githubusercontent.com/17583451/33156545-abe06402-d035-11e7-89ca-2aeeb882d2e0.png)
