### ISSUE TITLE
star不了？

### ISSUE THREAD

**Issue by zhan-ge** [jkpang/PPHub-Feedback#21]
rt

运行环境: iPhone SE - iOS11.1 - PPHub v1.0.0(1)

**Comment by jkpang** [comment]
请问是在哪个界面Star不了?  
repo列表还是repo详情界面? 
Star仓库的时候会有什么表现, 是App顶部弹出红色横幅提示Star失败? 还是任何反应都没有? @zhan-ge

**Comment by jkpang** [comment]
我这边是可以Star的, v1.0.1今天已通过苹果审核, 在仓库详情页优化了Star/Watch/Fork的操作
