### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by shixukai** [jkpang/PPHub-Feedback#22]
消息标签打不开，一点就崩

运行环境: iPhone 7 Plus - iOS11.1.2 - PPHub v1.0.0(1)

**Comment by jkpang** [comment]
最新版本1.0.1已经尝试对该问题的修复, 昨天已经提交苹果审核, 但是苹果团队在23 - 26日过感恩节, 所以可能要到下周一才审核通过了
![image](https://user-images.githubusercontent.com/17583451/33174420-e93c16a4-d092-11e7-9624-6c476c4d3969.png)
![image](https://user-images.githubusercontent.com/17583451/33174429-fc7b1c06-d092-11e7-8968-2c893ca58e5d.png)

**Comment by jkpang** [comment]
V1.0.1今天已通过苹果审核, 新版本已修复该问题
