### ISSUE TITLE
建议添加软件语言设置

### ISSUE THREAD

**Issue by pxisd** [jkpang/PPHub-Feedback#23]
英语和 Gayhub 更搭……
希望可以添加语言的设置。

运行环境: iPhone 7 - iOS11.1.2 - PPHub v1.0.0(1)

**Comment by jkpang** [comment]
好的, 我会在后续的版本中完善这个功能 @pxisd

**Comment by jkpang** [comment]
v1.1.0已上架App Store, 已添加手动切换语言的功能
