### ISSUE TITLE
添加显示有多少 star 的功能

### ISSUE THREAD

**Issue by Draveness** [jkpang/PPHub-Feedback#24]
Environment: iPhone X - iOS11.1.2 - PPHub v1.0.0(1)

**Comment by jkpang** [comment]
请问左神说的是用户个人主页的Star数吗?
GitHub官方提供的接口里面没有Star数这个字段, 我会考虑在后续的版本中添加这一选项 @Draveness

**Comment by Draveness** [comment]
就是统计下有多少 star 这样😂

**Comment by jkpang** [comment]
是统计自己Star了多少个Repo? 还是自己的Repo合起来获得了多少个Star? 😂

**Comment by Draveness** [comment]
后者...

Regards,
Draveness

**Comment by jkpang** [comment]
下个版本左神就可以看见自己个人的总Star数啦 @Draveness

**Comment by Draveness** [comment]
厉害啦，哈哈哈

**Comment by jkpang** [comment]
1.2.0版本已更新，左神更新后可以进入Profile界面，点击右上角图标进入，登录后即可查看自己GitHub账号的具体分析

**Comment by Draveness** [comment]
👍
