### ISSUE TITLE
launch image

### ISSUE THREAD

**Issue by Asura19** [jkpang/PPHub-Feedback#25]
启动页还是别写你的名字吧，丑，low

运行环境: iPhone X - iOS11.2 - PPHub v1.0.0(1)

**Comment by jkpang** [comment]
老哥不要说的这么直白嘛, 我下下个版本就去掉😂 😂 😂 (新版本周四就提交了, 因为感恩节,还没审核通过) @Asura19

**Comment by Asura19** [comment]
好的老哥，我错了，以后委婉一点~嘿嘿嘿

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jkpang** [comment]
App Store的最新版本1.0.2已经去掉了哦, 如果更新后还发现有, 可以卸载后重新安装 @Asura19

**Comment by Asura19** [comment]
以后会有查看代码的功能吗

**Comment by jkpang** [comment]
会有的老哥, 这些功能我会慢慢加上去的, 工作日每天只有2个小时在家搞设计/敲代码, 需要时间😂

**Comment by Asura19** [comment]
@jkpang 好的好的, 加油哦! 看好你

**Comment by jkpang** [comment]
谢谢支持哈 @Asura19
