### ISSUE TITLE
v1.0.1(4) - 二级页面下面放readme

### ISSUE THREAD

**Issue by nerozhao** [jkpang/PPHub-Feedback#26]
了解项目基本都要看readme,这样就能少点一次

运行环境: iPhone X - iOS11.1.2 - PPHub v1.0.1(4)

**Comment by jkpang** [comment]
这几天我试了在仓库详情界面放Readme, 代码实现起来很简单, 但是最终的体验不是很好(因为加载readme是异步的, 快速上下滑动界面会出现跳动), 我尝试过很多方案都达不到完美的体验, 所以暂时我还不会将Readme放置在二级界面,等以后完美解决这个问题后再上. 
不过现在我已极大的改进优化了Readme显示效果, 去除了与readme无关的内容, 让你更纯粹的浏览readme @nerozhao

**Comment by jkpang** [comment]
v1.4.0已审核通过，已将readme移至二级界面
