### ISSUE TITLE
Display emoji in repo's description field

### ISSUE THREAD

**Issue by Sorosliu1029** [jkpang/PPHub-Feedback#27]
If emoji is in such format like `:tada:`, Github could render it as :tada:, but PPHub will not render it and display as raw.
See [this repo](https://github.com/Sorosliu1029/Rule-based_Expert_System), its description is '🎓🐬Course Project: Artificial Intelligence', but not `:mortar_board::dolphin:Course Project: Artificial Intelligence`

**Comment by jkpang** [comment]
I'm very sorry, this is the JSON data returned to me by GitHub API. I've tried a lot of solutions that can't be solved perfectly for the time being.
