### ISSUE TITLE
v1.0.1(4) - 本次更新后还是看不了私有库

### ISSUE THREAD

**Issue by ntian2** [jkpang/PPHub-Feedback#29]
运行环境: iPhone 7 - iOS11.1.2 - PPHub v1.0.1(4)

**Comment by jkpang** [comment]
这就尴尬了我自己没有GitHub的付费账号,建不了私有仓库😂 , 那这样,我给你开通下苹果的内测权限, 我今天下班回家传一个测试包上去, 你再看看. 希望能留一下你的邮箱哈,内测用

**Comment by ntian2** [comment]
n1179953947@gmail.com 麻烦你了. 因为我还是学生 所以我申请的GitHub Student Package

**Comment by jkpang** [comment]
没事没事, 我大概知道原因了, 今晚上传的测试包应该可以解决, 感谢!

**Comment by jkpang** [comment]
或者你加下我QQ: 2406552315, 到时候你的gmail邮箱因为墙的原因可能不能及时收到邮件
