### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by mpasr** [jkpang/PPHub-Feedback#3]
修改资料闪退

运行环境: iPhone 7 - iOS10.3.3 - PPHub v1.0.0(1)

**Comment by jkpang** [comment]
请问是修改哪一项资料的时候闪退? 我这边没有复现 @mpasr

**Comment by jkpang** [comment]
请问是在修改个人简介时粘贴文本产生的崩溃吗?

**Comment by mpasr** [comment]
不是,是根本点不进去，点任何一项都闪退


发自我的 iPhone

**Comment by jkpang** [comment]
原因已找到, 下个版本更新修复, 感谢反馈😊

**Comment by jkpang** [comment]
V1.0.1 has passed the apple audit today, and the new version has repaired the problem
V1.0.1今天已通过苹果审核, 新版本已修复该问题
