### ISSUE TITLE
v1.8.0(73) - 0 star 也会上榜单

![图片](...

### ISSUE THREAD

**Issue by Quorafind** [jkpang/PPHub-Feedback#3]
0 star 也会上榜单

![图片](https://i.loli.net/2019/01/07/5c32d53c53eaf.png)

运行环境: iPhone 7 - iOS12.0.1 - v1.8.0(73)

**Comment by jkpang** [comment]
嗯嗯，这是官方的Trending榜数据，有些仓库没有显示出今日Star的数量，我就把这个数字设置为0了 @Quorafind

**Comment by Quorafind** [comment]
@jkpang 好的，我还以为是 BUG。不是就行。辛苦了，加油

**Comment by jkpang** [comment]
感谢反馈😊 @Quorafind

**Comment by jkpang** [comment]
非常抱歉，这个是我这边数据解析的问题，在仓库没有编程语言的时候会出现这个问题，下个版本我将修复，感谢反馈 @Quorafind

**Comment by jkpang** [comment]
你好，v1.8.1已通过审核，已修复了这个问题，快去更新吧 @Quorafind
