### ISSUE TITLE
Suggestion: add first-level star button on repo's detail page

### ISSUE THREAD

**Issue by Sorosliu1029** [jkpang/PPHub-Feedback#30]
RT, like `follow` button on github account's detail page. And move `···` button under star button (or remove `···` button completely).
From my experience, I will only star a repo if interested, not watch it or fork it first. So it makes sense to add a first-level star button, to avoid touching twice.
Just a suggestion.

**Comment by jkpang** [comment]
Thank you very much for your advice, and I will continue to pay attention to this issue in a subsequent version.

**Comment by Sorosliu1029** [comment]
Already implemented in latested version
