### ISSUE TITLE
v1.0.1(4) - Trending Tab 不显示内容

### ISSUE THREAD

**Issue by wao1201** [jkpang/PPHub-Feedback#32]
如题，刷新了只显示 No requests to data （设置为显示月统计）

另，是否可增加个选项用来选择启动 app 时默认显示哪个 tab？例如我想要启动 app 时显示 News，而不是现在的 Trending

谢谢

Environment: iPhone 6s Plus - iOS11.1.2 - PPHub v1.0.1(4)

**Comment by jkpang** [comment]
1. 如果你查看的是比较冷门的编程语言的Trending, 多次刷新列表提示没有数据, 那说明GitHub官网也是没有数据的, 这种情况我也遇到过. 可以查看网页版进行对比: https://github.com/trending
2. 默认启动Tab的需求我会考虑在后续的版本中添加
非常感谢您的反馈😊
