### ISSUE TITLE
V1.1.0 一点体验上的个人见解

### ISSUE THREAD

**Issue by ecmadao** [jkpang/PPHub-Feedback#38]
1. 希望在个人的  repositories, followers, following 这些 tab 下的列表里面，各条目能够按照时间顺序倒叙排列（就像官网那样）。因为用户最关心的更可能是近期的更新，比如今天新增的 follower 是谁。不过我记得 api 或许到的数据应该是顺序排列的，需要做个排序。
2. 接上面那条，除了一个排序方式，也可以提供顺序/倒叙排列
3. 希望头像和右侧最上一行的文字能够对齐（虽然可能实际上已经对齐了。。但是视觉上没有，看着会有点难受）。如图：![](http://obpykithy.bkt.clouddn.com/WechatIMG304.jpeg)
4. 还是上面那张图，次要信息的字体颜色可以再淡一些，比如最下面的 'update xx hours ago'
5. Trending 页面下，仓库的介绍和上面的仓库名称希望可以左对齐，如下图：![](http://obpykithy.bkt.clouddn.com/WechatIMG303.jpeg)

还有一点 UI 优化，比如 trending 里面排名的标签不是很好看，不太好表述 😂 就先暂时这些吧，我之后使用过程中有啥想法就在后面继续加

**Comment by jkpang** [comment]
大佬, 您提的第3, 4点 还有trending 里面排名的标签已修改优化, 
剩下的几点在后续的版本中我再看看是否加进去, 感谢大佬的建议!

**Comment by ecmadao** [comment]
@jkpang 
COOOOL！酷呆了！
