### ISSUE TITLE
v1.1.0(9) - 查看代码页面缩放

### ISSUE THREAD

**Issue by Asura19** [jkpang/PPHub-Feedback#39]
运行环境: iPhone X - iOS11.2 - PPHub v1.1.0(9)

**Comment by jkpang** [comment]
v1.1.1已发布, 请到App Store更新哦

**Comment by Asura19** [comment]
@jkpang  好的看到了, 给您评了个五星, 嘿嘿.  另外以后会加上Notifications功能吗

**Comment by jkpang** [comment]
感谢好评!😊 , 您说的Notifications是推送还是GitHub的Notifications消息? @Asura19

**Comment by Asura19** [comment]
github的通知, 我想在PPHub里和你交流意见

**Comment by jkpang** [comment]
OK, Notifications会考虑在以后的版本加入进去的, 感谢
