### ISSUE TITLE
v1.1.0(9) - 可否增加jupyter notebook进行优化

### ISSUE THREAD

**Issue by TioWang** [jkpang/PPHub-Feedback#40]
对.ipynb文件用桌面站点模式打开。只是一个想法~

运行环境: iPhone X - iOS11.2 - PPHub v1.1.0(9)

**Comment by jkpang** [comment]
正在着手解决😊

**Comment by jkpang** [comment]
v1.1.1已发布, 请到App Store更新哦

**Comment by TioWang** [comment]
貌似没有变化😳
![c717af6b-ce2b-405c-b716-554ec6d70bb7](https://user-images.githubusercontent.com/12782946/34086895-85681848-e3da-11e7-81e6-0af7574181bb.png)

**Comment by jkpang** [comment]
😥 😥 😥看来.ipynb文件没有被识别为文本文件, 我再想想办法 @TioWang

**Comment by jkpang** [comment]
v1.1.2已经可以使用桌面站点模式打开.ipynb文件了, 更新看看哈

**Comment by jkpang** [comment]
你好，v1.9.0已审核通过，现在已可以查看.ipynb文件 @stevewongv
