### ISSUE TITLE
v1.1.0(9) - 希望能加入查看自己star功能

### ISSUE THREAD

**Issue by yihong0618** [jkpang/PPHub-Feedback#41]
作者您好，这次更新太棒了，非常感谢作者带来这么好的应用。

运行环境: iPhone 7 - iOS11.2 - PPHub v1.1.0(9)

**Comment by jkpang** [comment]
您好, PPHub是可以查看自己或其他用户Star的仓库的, 点击个人界面的Repos/Followers/Following任一按钮, 进入下一个界面, 左滑动第四个就是自己Star的仓库
非常感谢您对PPHub的支持😊 
![image](https://user-images.githubusercontent.com/17583451/33792992-da045cd8-dce9-11e7-9e1b-db4ead2265cb.png)![image](https://user-images.githubusercontent.com/17583451/33792994-e707ca5a-dce9-11e7-9096-9de355104821.png)

**Comment by yihong0618** [comment]
谢谢作者，已经找到了，辛苦。




  
  
  


  
    
      
          
            
              
            
            
              洪伊
            
          
            
              
                  邮箱：zouzou0208@gmail.com
              
            
      
    
  


签名由 网易邮箱大师 定制
在2017年12月09日 14:05，jkpang 写道： 您好, PPHub是可以查看自己或其他用户Star的仓库的, 点击个人界面的Repos/Followers/Following任一按钮, 进入下一个界面, 左滑动第四个就是自己Star的仓库
非常感谢您对PPHub的支持😊


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jkpang/PPHub-Feedback","title":"jkpang/PPHub-Feedback","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jkpang/PPHub-Feedback"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jkpang in #41: 您好, PPHub是可以查看自己或其他用户Star的仓库的, 点击个人界面的Repos/Followers/Following任一按钮, 进入下一个界面, 左滑动第四个就是自己Star的仓库\r\n非常感谢您对PPHub的支持😊 \r\n![image](https://user-images.githubusercontent.com/17583451/33792992-da045cd8-dce9-11e7-9e1b-db4ead2265cb.png)![image](https://user-images.githubusercontent.com/17583451/33792994-e707ca5a-dce9-11e7-9096-9de355104821.png)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/jkpang/PPHub-Feedback/issues/41#issuecomment-350426792"}}}

**Comment by jkpang** [comment]
不客气哈, 感谢使用PPHub!😊
