### ISSUE TITLE
v1.1.0(9) - Landscape Mode

### ISSUE THREAD

**Issue by jazi4** [jkpang/PPHub-Feedback#42]
Just bought your App Today
Please can you add Landscape Mode , as I use my iPad on a special stand
with speakers etc , which makes it very difficult to rotate. 

Environment: iPad 4 - iOS10.3.1 - PPHub v1.1.0(9)

**Comment by jkpang** [comment]
The version of the v1.1.1 has been updated. Now it has supported the Landscape mode and goes to the App Store update.
