### ISSUE TITLE
横屏转竖屏出现显示问题

### ISSUE THREAD

**Issue by TioWang** [jkpang/PPHub-Feedback#49]
iPhone X上出现详情看图
![443b50bf-81ab-4be9-ac15-1158ef56c288](https://user-images.githubusercontent.com/12782946/34085234-3dca2d08-e3c8-11e7-85e5-f1334d498800.png)

**Comment by jkpang** [comment]
最新版本1.1.2已修复iPhoneX横屏切换竖屏后界面变窄的bug. 但横竖屏切换还是有需要优化的地方, 这个优化需要点时间, 在后续的版本中会解决, 感谢支持!
