### ISSUE TITLE
v1.1.2(11) - 视图错误

### ISSUE THREAD

**Issue by Joe0708** [jkpang/PPHub-Feedback#51]
Profile-Followers 界面中视图被导航栏遮挡

运行环境: iPhone X - iOS11.2.5 - PPHub v1.1.2(11)

**Comment by jkpang** [comment]
恩恩, 已发现这个问题, 下个版本更新解决, 感谢反馈 @Joe0708

**Comment by jkpang** [comment]
1.2.0版本已更新，已修复这个问题，快去更新吧
