### ISSUE TITLE
v1.1.2(11) - 关于超链接处理的建议

### ISSUE THREAD

**Issue by EyreFree** [jkpang/PPHub-Feedback#52]
1. 可以考虑处理 README 等处的 URL 跳转，监测到 App 内已存在原生页面的可以直接跳转到对应的原生页面（比如仓库或用户页面等）；

2. 可以考虑添加 ShareExtension 等的应用，从 QQ 或微信等 App 内通过系统分享对话框将内容（主要是超链接）分享给 PPHub 然后按第一条中的方式打开对应原生页面。

**Comment by jkpang** [comment]
PPHub v1.3.2已审核通过， 已增加对超链/Extensiond处理， 快去更新哦！
