### ISSUE TITLE
v1.1.2(11) - 可不可以支持下 Opener

### ISSUE THREAD

**Issue by jerryismy** [jkpang/PPHub-Feedback#54]
作者你好，不知道有计划联系 opener 那边支持一下吗，浏览器跳转到 PPhub 就方便了，谢谢！

运行环境: iPhone 6s Plus - iOS11.2.5 - PPHub v1.1.2(11)

**Comment by jkpang** [comment]
好的, 这个我会尝试下 @jerryismy

**Comment by jkpang** [comment]
正在与Opener作者沟通, 请等待.... @jerryismy

**Comment by jkpang** [comment]
![image](https://user-images.githubusercontent.com/17583451/34973508-fafd1708-fac2-11e7-9ee1-4de11e802a8a.png)
![image](https://user-images.githubusercontent.com/17583451/34973518-043e611e-fac3-11e7-9aef-2747e5270e15.png)

**Comment by jerryismy** [comment]
哈哈，看来有眉目了呀，期待期待！

--  
jerry  

在 2018年1月16日 at 09:42:59, jkpang (notifications@github.com(mailto:notifications@github.com)) 写到:
