### ISSUE TITLE
v1.2.0(14) - 建议将仓库拿出来放到底部栏

### ISSUE THREAD

**Issue by wangduanduan** [jkpang/PPHub-Feedback#56]
第一次使用，想找自己star过的项目也太难了，要好几层才能找到。我觉得仓库栏应该放在底部。

第二，仓库里建议增加搜索功能，项目太多了，搜索太难。

运行环境: iPhone 6s - iOS10.3.2 - PPHub v1.2.0(14)

**Comment by jkpang** [comment]
感谢建议, 在未来的版本中我会考虑加上您的建议(不一定能在正式版上这些功能, 但我一定会尝试😊 , 感谢 ) @wangduanduan

**Comment by jkpang** [comment]
最新版中，用户自己Star的仓库已单独抽离出来放入底栏。搜索自己Star的仓库，因为GitHub官方没有提供对应的接口，暂时无法实现，感谢反馈
