### ISSUE TITLE
v1.2.0(14) - news 中的 forked 显示模式

### ISSUE THREAD

**Issue by ChengLuffy** [jkpang/PPHub-Feedback#57]
一些我知道的 repo 被我关注的人 forked ，我会去关注他做了什么修改，所以建议显示 forked 后的 地址，以及，commit messages 的显示

运行环境: iPhone 6 - iOS11.2.1 - PPHub v1.2.0(14)

**Comment by jkpang** [comment]
v1.2.1已通过App Store审核, forked 后的地址已加上
commit messages显示会在后续版本中优化 @ChengLuffy
