### ISSUE TITLE
关闭按钮位置不统一

### ISSUE THREAD

**Issue by queuey** [jkpang/PPHub-Feedback#6]
提个建议，你那个关闭按钮能不能统一下。一会在左边一会在右边，简直要爆炸

运行环境: iPhone 6 - iOS11.1.2 - PPHub v1.0.0(1)

**Comment by jkpang** [comment]
V1.0.1 has passed the apple audit today, and the new version has repaired the problem
V1.0.1今天已通过苹果审核, 新版本已修复该问题
