### ISSUE TITLE
v1.8.0(73) - 没有git clone功能吗？

### ISSUE THREAD

**Issue by sleep39** [jkpang/PPHub-Feedback#6]
运行环境: iPhone 8 Plus - iOS12.1.2 - v1.8.0(73)

**Comment by jkpang** [comment]
你好，没有这个功能哦，个人认为在移动设备上对仓库进行git clone操作的意义不大，体现不出生产力。git clone还是得在桌面端 @sleep39

**Comment by sleep39** [comment]
好吧T_T，以后会加入编辑文本的功能吗
@jkpang

**Comment by jkpang** [comment]
文本编辑不确定。个人感觉在手机上写代码很别扭（除非移动端专业的编辑器），要是写错了个符号push上去，还可能会造成事故，有点危险 @sleep39

**Comment by sleep39** [comment]
主要还是想写点文档，私库免费之后想弃用其它的笔记账户，只留一个github来写东西。
我再研究研究IFTTT看看，总之谢谢答复( ⁼̴̀ .̫ ⁼̴́ )✧。
@jkpang

**Comment by jkpang** [comment]
嗯嗯，也非常感谢您的反馈😊 @sleep39
