### ISSUE TITLE
v1.2.0(14) - 搜索的时候闪退

### ISSUE THREAD

**Issue by liyafly** [jkpang/PPHub-Feedback#62]
在搜索的时候闪退 搜索关键词是iOS-Weekly

运行环境: iPhone 6s - iOS11.2.1 - PPHub v1.2.0(14)

**Comment by jkpang** [comment]
OK, 已知悉, 今晚下班后处理

**Comment by jkpang** [comment]
你好, PPHub v1.2.1已通过App Store审核, 已修复这个bug @liyafly
