### ISSUE TITLE
v1.2.0(14) - [Crash]Search for something cause the app crash

### ISSUE THREAD

**Issue by oneofai** [jkpang/PPHub-Feedback#64]
App will crash When I search ‘iOSProject’

Environment: iPhone 6s Plus - iOS11.2.2 - PPHub v1.2.0(14)

**Comment by jkpang** [comment]
This bug has been resolved, waiting for the next release

**Comment by jkpang** [comment]
Hello, PPHub V1.2.1 has been approved by App Store and has been restored to this bug
