### ISSUE TITLE
v1.2.2(19) - 希望增加 raw 地址查看。

### ISSUE THREAD

**Issue by 0x00000cc** [jkpang/PPHub-Feedback#68]
你好，好多需要用到 raw 地址的地方，增加这个更加方便，或者说已经有了这个功能吗？

运行环境: iPhone 7 - iOS11.3 - PPHub v1.2.2(19)

**Comment by jkpang** [comment]
目前的版本还没有这个功能，查看raw地址会在以后的版本中添加

**Comment by jkpang** [comment]
现在最新版本已可以查看仓库文件的RAW内容
