### ISSUE TITLE
v1.8.0(73) - 无法查看所有历史commits记录，co...

### ISSUE THREAD

**Issue by Biiiiz** [jkpang/PPHub-Feedback#7]
无法查看所有历史commits记录，commits下拉更新记录时出来的都是第一次commit的记录，这点请关注修改。

Environment: iPhone XS - iOS12.1.2 - v1.8.0(73)

**Comment by jkpang** [comment]
你好，可以告知您是看的哪个仓库的Commits吗？我刚刚比对了网页版和PPHub的Commits数据是一致的，PPHub的Commits列表下拉刷新是最新数据，每页30条数据，上拉会加载第2页数据，再次上拉会加载第3页.....以此类推 @Biiiiz

**Comment by jkpang** [comment]
可以通过PPHub内的 关于-QQ群，加群或者加我个人QQ。
还有你提交代码是在主分支吗，可能你在其他分支提交了没有合并到主分支所以看不到 @Biiiiz

**Comment by Biiiiz** [comment]
一定要合并到master才能正常显示commit history吗？有些仓库确实有自己新建branch，这种branch不能显示commit吗？

**Comment by jkpang** [comment]
> ok，麻烦了，你的这个app是目前我用过的最好的GitHub三方应用了，期待持续改进，谢谢。
感谢❤

**Comment by jkpang** [comment]
下个版本将优化这个问题，到时候在仓库详情页切换分支就可以看到对应的commits了 @Biiiiz

**Comment by Biiiiz** [comment]
感谢您的支持，另外还有一个小建议，就是在commits界面下拉后如果已经加载出了所有history以后就不要一直返回最后一次commit的记录了，只显示一次即可，希望采纳，谢谢。

**Comment by jkpang** [comment]
> 感谢您的支持，另外还有一个小建议，就是在commits界面下拉后如果已经加载出了所有history以后就不要一直返回最后一次commit的记录了，只显示一次即可，希望采纳，谢谢。

你好，我没有太明白这个意思。PPHub 的下拉刷新是加载最新第一页的数据，上拉加载第2，3，4...页的数据，此逻辑与网页的上一页，下一页的逻辑一样 @Biiiiz

**Comment by Biiiiz** [comment]
commits界面中，每次下拉更新以后，都会刷新出来一次最新版本的commit，下拉刷新n次，就显示n次相同的记录，我的意思是如果下拉后已经显示出了所有的commits记录，那么再次下拉时就直接提示已无更多记录，最终实现的效果就是commits history界面只显示一组所有的记录即可。

**Comment by jkpang** [comment]
- commits界面中，每次下拉更新以后，都会刷新出来一次最新版本的commit，下拉刷新n次，就显示n次相同的记录，我的意思是如果下拉后已经显示出了所有的commits记录，那么再次下拉时就直接提示已无更多记录，最终实现的效果就是commits history界面只显示一组所有的记录即可。

明白了，我刚刚复现了，这是Bug，感谢反馈，下个版本修复 @Biiiiz

**Comment by Biiiiz** [comment]
OK，期待您的持续改善，非常感谢。

**Comment by jkpang** [comment]
1.8.2已可以查看其他分支的Commits（仓库详情页切换分支后，再进入Commits查看），快去更新吧 @Biiiiz

**Comment by Biiiiz** [comment]
ok，感谢。
