### ISSUE TITLE
v1.2.2(19) - 视图错误

### ISSUE THREAD

**Issue by iJasonY** [jkpang/PPHub-Feedback#70]
Repositories/Developers 界面列表中最后一个cell被TabBar遮挡了

运行环境: iPhone 7 Plus - iOS10.3.3 - PPHub v1.2.2(19)

**Comment by jkpang** [comment]
已知悉, 此Bug在iOS11以下的系统会出现, 我会尽快解决这个bug, 感谢你的反馈 @iJasonY

**Comment by jkpang** [comment]
v1.3.0已审核通过, 已修复这个问题
