### ISSUE TITLE
v1.2.2(19) - 能不能把star之类的功能变成直观的按钮呢？

### ISSUE THREAD

**Issue by iblueer** [jkpang/PPHub-Feedback#71]
每次Star还得点二级菜单进去，感觉很麻烦。尤其是iPad上，按钮在右上角，离操作热区太远了。

运行环境: iPad Pro - iOS11.2.5 - PPHub v1.2.2(19)

**Comment by jkpang** [comment]
好的, 这个在后续的版本会调整, 谢谢建议 @iblueer

**Comment by jkpang** [comment]
PPHub v1.3.2已审核通过， 已解决此问题， 快去更新哦！
