### ISSUE TITLE
v1.2.2(19) - 流行仓库列表最后一个显示不全

### ISSUE THREAD

**Issue by lemontree2000** [jkpang/PPHub-Feedback#72]
如题

运行环境: iPhone 6s - iOS10.2 - PPHub v1.2.2(19)

**Comment by jkpang** [comment]
这个问题在iOS11以下的系统会出现, 下个版本会修复, 感谢你的反馈 #70

**Comment by jkpang** [comment]
v1.3.0已审核通过, 已修复这个问题
