### ISSUE TITLE
v1.2.2(19) - 不支持换行差评

### ISSUE THREAD

**Issue by yonghuming** [jkpang/PPHub-Feedback#76]
代码不能自动换行差评
但是界面很漂亮
不知道什么框架开发的

运行环境: iPhone 6 - iOS11.0.3 - PPHub v1.2.2(19)

**Comment by yl-zhang** [comment]
swift

**Comment by jkpang** [comment]
v1.6.0已通过审核，查看代码已支持换行 @yonghuming
