### ISSUE TITLE
v1.3.0(24) - 感觉亏大了

### ISSUE THREAD

**Issue by omaidb** [jkpang/PPHub-Feedback#79]
1.99刀入手的，issue还是调用浏览器，感觉不太好，能做的更有逼格一点么

运行环境: iPhone 7 Plus - iOS11.2.6 - PPHub v1.3.0(24)

**Comment by jkpang** [comment]
查看issue详情我目前还没找到比较完美的原生显示方式，您说的“更有逼格”在后续版本可能会上。您觉得买的不值是可以找苹果申请退款的哈(点击苹果收据邮件中的报告问题，选择您的理由，即可申请退款)。

**Comment by omaidb** [comment]
老板你不要这样，我只是想鞭策你
jkpang <notifications@github.com>于2018年3月7日 周三10:04写道：

**Comment by jkpang** [comment]
不不不, 您才是老板, 谢谢鞭策, 我会努力的😂😂😂  @omaidb
