### ISSUE TITLE
v1.3.1(25) - 一个很奇怪的问题

### ISSUE THREAD

**Issue by Quorafind** [jkpang/PPHub-Feedback#81]
您好，当我用手机访问xitu/tensorflow-docs该仓库的README的时候，尽管应该是显示为中文的，但是实际显示却是英文的。我认为是不是Branch默认跳转为第一个branch了呢？链接如(tensorflow-docs)[https://github.com/xitu/tensorflow-docs]。而且复制后进入pphub也会显示不存在这个仓库。您可以用PPHUB查找xitu的这个仓库后尝试一下。除了这个以外，您的这个软件真的很好，很喜欢。

运行环境: iPhone 7 - iOS10.3.3 - PPHub v1.3.1(25)

**Comment by jkpang** [comment]
啊啊, 非常感谢您的反馈,我会尽快解决这个问题 (最近事情太多了, 非常抱歉) @Quorafind

**Comment by jkpang** [comment]
PPHub v1.3.2已审核通过， 已解决此问题， 快去更新哦！
