### ISSUE TITLE
v1.3.1(25) - issue

### ISSUE THREAD

**Issue by droid-Q** [jkpang/PPHub-Feedback#85]
airdrop rep 到macos chrome 会在download目录出现一个图标文件。

运行环境: iPhone X - iOS11.3 - PPHub v1.3.1(25)

**Comment by jkpang** [comment]
是的， 这是正常的。这是iOS系统自带的分享功能， 我这边还无法控制当分享方式为AirDrop时，改变分享内容 @droid-Q
