### ISSUE TITLE
UI Issue: overlay

### ISSUE THREAD

**Issue by Sorosliu1029** [jkpang/PPHub-Feedback#86]
![img_1448](https://user-images.githubusercontent.com/8862646/37690926-331587ee-2ce9-11e8-8245-d93d5968d15f.jpg)
A picture is worth a thousand words.

P.S: Could develop a feature to let user upload screenshot inside app's feedback page? So they do not need to open new issue through GitHub web page (like I am doing now ... Orz)

**Comment by jkpang** [comment]
Thank you for your feedback, and I'll solve it in the next version

**Comment by jkpang** [comment]
V1.3.2 has been updated to solve this Bug
