### ISSUE TITLE
UI Issue: animation inconsistency

### ISSUE THREAD

**Issue by Sorosliu1029** [jkpang/PPHub-Feedback#88]
In 'Repositories' page of trending page, slide to right and release, the title 'Repositories' will go back to center **smoothly**, while in 'Developers' page,  the title 'Developers' will **jump** back to center.

**Comment by jkpang** [comment]
Thanks for feedback, this problem is more difficult to solve, I will try to make PPHub more perfect, thank you very much! 😂😂😂
