### ISSUE TITLE
Repo detail page UI confusion

### ISSUE THREAD

**Issue by Sorosliu1029** [jkpang/PPHub-Feedback#9]
In a repo's detail page, there is a right sharp bracket icon `>` which might lead user to click, but actually nothing happens. Does it intend to navigate to a web view of this specific repo?

**Comment by jkpang** [comment]
This is actually a long pop up menu, but I haven't found an interactive cue yet. I'll try to optimize this problem, thank you very much!
**********************
这其实是一个长按弹出菜单的操作, 只是我暂时没有找到一个号的交互提示, 我会想办法优化这个问题的, 非常感谢! @Sorosliu1029

**Comment by jkpang** [comment]
V1.0.1 has passed the apple audit today, and the new version has repaired the problem
V1.0.1今天已通过苹果审核, 新版本已修复该问题
