### ISSUE TITLE
v1.3.1(25) - 发现一个bug

### ISSUE THREAD

**Issue by windstormeye** [jkpang/PPHub-Feedback#90]
查看每日最热项目时，如果时间过长，star和fork会超过cell的宽度，和...挤在一块。初步估计是约束漏了

运行环境: iPhone 7 - iOS11.2.6 - PPHub v1.3.1(25)

**Comment by jkpang** [comment]
这个BUG已经解决了，今天v1.3.2版本已经审核通过， 快去更新哦 @windstormeye
