### ISSUE TITLE
v1.3.1(25) - 更新提示

### ISSUE THREAD

**Issue by Evrins** [jkpang/PPHub-Feedback#91]
1.3.2 提示更新 1.3.2 
为什么应用更新完自己实现，直接走 App Store 不好么？

Environment: iPhone 8 Plus - iOS11.2.6 - PPHub v1.3.1(25)

**Comment by jkpang** [comment]
emmm...... 我是想让用户第一时间用上最新版的PPHub ，App Store 的更新提示在不打开的情况下会延迟1到2天。😄

**Comment by Evrins** [comment]
App Store 上显示我是最新的，但是提交反馈的时候显示的是 1.3.1(25)

**Comment by jkpang** [comment]
App Store有缓存，你杀掉App Store的进程重新进去试试 @Evrins
