### ISSUE TITLE
v1.3.2(26) - 关于用户体验的小意见

### ISSUE THREAD

**Issue by windstormeye** [jkpang/PPHub-Feedback#92]
提个小意见，最新版本的更新出来的star和follow，如果加上Tapic engine交互呢？我觉得之前的交互震动感比较好。。（只是个意见哈😅）

运行环境: iPhone 7 - iOS11.2.6 - PPHub v1.3.2(26)

**Comment by jkpang** [comment]
哈哈， 谢谢建议哈！给Star、Follow按钮加上Tapic engine交互我会考虑， 现在PPHub中还是有好几个地方用了Tapic engine， 我怕调用的地方太多了也不好。上次还有用户说调用Tapic engine的地方太多了呢😂 ， 一千个人心中有一千个哈姆雷特😂 😂 😂
