### ISSUE TITLE
v1.3.2(26) - star藏的太深了

### ISSUE THREAD

**Issue by CyshallChan** [jkpang/PPHub-Feedback#93]
如题，可以不可以挪出来呀？

Environment: iPhone 8 Plus - iOS11.2.6 - PPHub v1.3.2(26)

**Comment by jkpang** [comment]
下个版本会考虑挪出来, 单独一个Star模块. 因为最近忙着离职交接和找工作, 所以更新的计划会慢一点. @CyshallChan

**Comment by jkpang** [comment]
v1.4.0审核通过，已将个人Star仓库独立出来
