### ISSUE TITLE
v1.3.2(26) - 通知的位置蓋住status bar

### ISSUE THREAD

**Issue by AllenGuan** [jkpang/PPHub-Feedback#96]
![img_2385](https://user-images.githubusercontent.com/14134195/38215273-d72be368-36f9-11e8-966b-f9456567f761.PNG)

Environment: iPhone 6s Plus - iOS11.3 - PPHub v1.3.2(26)

**Comment by jkpang** [comment]
v1.4.0版本已审核通过，已优化这个问题
